<?php

namespace Aegir\Hostmaster\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceAssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceAssetRepository extends EntityRepository
{
}
