aegir_store:
    resource: "@AegirStoreBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc


AegirHostmaster:
    resource: "@AegirHostmaster/Resources/config/routing.yml"
