
_server:
    resource: "@AegirHostmaster/Controller/ServerController.php"
    type:     rest

_project:
    resource: "@AegirHostmaster/Controller/ProjectController.php"
    type:     rest

_welcome:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: get_servers
        permanent: true # this for 301